### PR TITLE
Update link

### PR DESCRIPTION
**Pull request by pingsutw**
Screenshot from 2020-06-15 12-03-14

### CODE REVIEW

**Comment by jiwq** [comment]
I'm not sure which path should be linked, such as 'https://github.com/apache/submarine/tree/master/docs/userdocs' or others. @wangdatan  @liuxunorg @tangzhankun Can you give some advice?

**Comment by wangdatan** [comment]
@jiwq , @pingsutw , I think we need 2 links to YARN/K8s README, since they're quite different now.

**Comment by pingsutw** [comment]
Thanks for the suggestion.
I've updated it and attached screenshot

**Comment by jiwq** [comment]
+1 LGTM Thanks @pingsutw works for this.

**Review by jiwq — APPROVED** [review]
+1 LGTM Thanks @pingsutw works for this.

**Pull request merged**
